interfaces:
  spine1:
    loopback: "10.2.1.3"
    int_numbered:
      swp49:
        ip_and_mask: "10.1.1.2/30"
      swp50:
        ip_and_mask: "10.1.1.6/30"
      swp51:
        ip_and_mask: "10.1.1.50/30"
      swp52:
        ip_and_mask: "10.1.1.54/30"
  spine2:
    loopback: "10.2.1.4"
    int_numbered:
      swp49:
        ip_and_mask: "10.1.1.18/30"
      swp50:
        ip_and_mask: "10.1.1.22/30"
      swp51:
        ip_and_mask: "10.1.1.34/30"
      swp52:
        ip_and_mask: "10.1.1.38/30"
  leaf1:
    loopback: "10.2.1.1"
    int_numbered:
      swp1s0:
        ip_and_mask: "10.1.1.1/30"
      swp1s1:
        ip_and_mask: "10.1.1.5/30"
      swp1s2:
        ip_and_mask: "10.1.1.33/30"
      swp1s3:
        ip_and_mask: "10.1.1.37/30"
    bonds:
      bond0:
        members: ["swp17","swp18"]    
    bridges:
      vlan_aware: 
        name: "bridge"
        pvid: "1"
        vid_start: "1"
        vid_stop: "100"
        members: ["swp32s0","bond0"]
        access_ports: 
          vlan10: ["swp32s0"]
        svi:
          bridge.10:
            ip_and_mask: "10.1.10.2/24"
  leaf2:
    loopback: "10.2.1.2"
    int_numbered:
      swp1s0:
        ip_and_mask: "10.1.1.17/30"
      swp1s1:
        ip_and_mask: "10.1.1.21/30"
      swp1s2:
        ip_and_mask: "10.1.1.49/30"
      swp1s3:
        ip_and_mask: "10.1.1.53/30"
    bonds:
      bond0:
        members: ["swp17","swp18"]
    bridges:
      vlan_aware: 
        name: "bridge"
        pvid: "1"
        vid_start: "1"
        vid_stop: "100"
        members: ["swp32s0","bond0"]
        access_ports: 
          vlan10: ["swp32s0"]
        svi:
          bridge.10:
            ip_and_mask: "10.1.10.3/24"




