---
- hosts: spine
  user: root
  roles:
    - common
    - ospfnum
  handlers:
    - include: handlers/main.yml

- hosts: leaf
  user: root
  roles:
    - common
    - ospfnum
  handlers:
    - include : handlers/main.yml
