interfaces:
  leaf1:
    loopback: "10.2.1.1"
    int_unnumbered: ["swp1","swp2","swp3"] 
    bridges:
      vlan_aware: 
        name: "bridge"
        pvid: "1"
        vid_start: "1"
        vid_stop: "100"
        members: ["swp4","swp5","swp6"]
        access_ports: 
          vlan10: ["swp4"]
        svi:
          bridge.10:
            ip_and_mask: "10.1.10.2/24"
  leaf2:
    loopback: "10.2.1.2"
    int_unnumbered: ["swp1","swp2","swp3"]
    bridges:
      vlan_aware: 
        name: "bridge"
        pvid: "200"
        vid_start: "200"
        vid_stop: "300"
        members: ["swp4","swp5", "swp6"]
        access_ports: 
          vlan210: ["swp4"]
        svi:
          bridge.210:
            ip_and_mask: "10.1.20.3/24"




